version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: library-mongo

  config-server:
    build: ./config-server
    restart: always
    container_name: config-server
    ports:
      - 5000:5000
    working_dir: /app

  backend:
    build: ./backend
    restart: always
    container_name: backend
    ports:
      - 8080:8080
    working_dir: /app
    depends_on:
      - mongo
      - config-server

  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    environment:
      - PORT=${PORT:-80}
    ports:
      - 8090:80
    depends_on:
      - backend