version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: library-mongo

  config-server:
    build: ./config-server
    restart: always
    container_name: config-server
    ports:
      - 5000:5000
    working_dir: /app
    depends_on:
      - eureka-server

  eureka-server:
    build: ./eureka
    restart: always
    container_name: eureka-server
    ports:
      - 8001:8001
    working_dir: /app

  zuul-server:
    build: ./zuul-service-gateway
    restart: always
    container_name: zuul-server
    ports:
      - 8765:8765
    working_dir: /app
    depends_on:
      - eureka-server

  backend:
    build: ./backend
    restart: always
    container_name: backend
    ports:
      - 8080:8080
    working_dir: /app
    depends_on:
      - eureka-server
      - config-server
      - mongo

  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    environment:
      - PORT=${PORT:-80}
    ports:
      - 8090:80
    depends_on:
      - backend