security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8081/authserver/oauth/token
      userAuthorizationUri: http://localhost:8081/authserver/oauth/authorize
      clientId: client
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:8081/authserver/user

logging:
  #  file: log/log.log
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG

